/* Generated by scripts/generate-icons.ts — do not edit */
export default function Home(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"currentColor\" d=\"M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8z\"/>" }}
    />
  );
}

Home.displayName = "mdi:home";
