const FrontendRedirectPaths = {
  home: '/',
  login: '/login',
  signup: '/signup',
  register: '/signup',
  forgotPassword: '/forgot-password',
  explore: '/explore',
  tasks: '/tasks',
  surveys: '/surveys',
  profile: '/profile',
  profileEarnings: '/profile/earnings',
  profileRedemptions: '/profile/redemptions',
  profileSettings: '/profile/settings',
  profileSessions: '/profile/sessions',
  affiliates: '/affiliates',
  redeem: '/redeem',
  leaderboard: '/leaderboard',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminWithdrawals: '/admin/withdrawals',
  adminEarnings: '/admin/earnings',
  adminPromocodes: '/admin/promocodes',
} as const;

export default FrontendRedirectPaths;
