const DatabaseCollections = {
  users: 'users',
  userSessions: 'userSessions',
  emailActionables: 'emailActionables',
  deletedAccountFingerprints: 'deletedAccountFingerprints',
  postbackLogs: 'postbackLogs',
  userEarnings: 'userEarnings',
  userNotifications: 'userNotifications',
  userTransactions: 'userTransactions',
  userRedemptions: 'userRedemptions',
  userFlags: 'userFlags',
  withdrawalAttestations: 'withdrawalAttestations',
  rewards: 'rewards',
  affiliateCodes: 'affiliateCodes',
  promocodes: 'promocodes',
  offers: 'offers',
  offerHistory: 'offerHistory',
  siteStatistics: 'siteStatistics',
  leaderboards: 'leaderboards',
  settings: 'settings',
  chatConversations: 'chatConversations',
  chatMessages: 'chatMessages',
};

export default DatabaseCollections;
