/* Generated by scripts/generate-icons.ts — do not edit */
export default function AltArrowDownLinear(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"m19 9l-7 6l-7-6\"/>" }}
    />
  );
}

AltArrowDownLinear.displayName = "solar:alt-arrow-down-linear";
