/* Generated by scripts/generate-icons.ts — do not edit */
export default function AltArrowRightLinear(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"m9 5l6 7l-6 7\"/>" }}
    />
  );
}

AltArrowRightLinear.displayName = "solar:alt-arrow-right-linear";
