/* Generated by scripts/generate-icons.ts — do not edit */
export default function ArrowLeftLinear(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"M20 12H4m0 0l6-6m-6 6l6 6\"/>" }}
    />
  );
}

ArrowLeftLinear.displayName = "solar:arrow-left-linear";
