/* Generated by scripts/generate-icons.ts — do not edit */
export default function CheckReadLinear(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"1.5\" d=\"m4 12.9l3.143 3.6L15 7.5m5 .063l-8.572 9L11 16\"/>" }}
    />
  );
}

CheckReadLinear.displayName = "solar:check-read-linear";
