/* Generated by scripts/generate-icons.ts — do not edit */
export default function ChecklistLinear(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="0 0 24 24"
      {...props}
      dangerouslySetInnerHTML={{ __html: "<g fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-width=\"1.5\"><path stroke-linejoin=\"round\" d=\"M2 5.5L3.214 7L7.5 3M2 12.5L3.214 14L7.5 10M2 19.5L3.214 21L7.5 17\"/><path d=\"M22 19H12m10-7H12m10-7H12\"/></g>" }}
    />
  );
}

ChecklistLinear.displayName = "solar:checklist-linear";
