import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { dirname, join, relative } from 'path';
import { getIconData, iconToSVG } from '@iconify/utils';

// Types
import type { IconifyJSON } from '@iconify/types';

const ROOT = join(import.meta.dir, '..');
const SRC_DIR = join(ROOT, 'src');
const ICONS_DIR = join(SRC_DIR, 'icons');
const GENERATED_HEADER = '/* Generated by scripts/generate-icons.ts — do not edit */';
const IMPORT_PATTERN = /from ['"]~icons\/([^/'"]+)\/([^/'"]+?)(?:\.jsx)?['"]/g;
const SOURCE_GLOB = new Bun.Glob('**/*.{ts,tsx,js,jsx}');

type IconRef = {
  set: string,
  name: string,
};

const collectionCache = new Map<string, IconifyJSON>();

function toComponentName(iconName: string): string {
  return iconName
    .split(/[-_]/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function iconPath({ set, name }: IconRef): string {
  return join(ICONS_DIR, set, `${name}.jsx`);
}

function iconKey({ set, name }: IconRef): string {
  return `${set}/${name}`;
}

async function loadCollection(set: string): Promise<IconifyJSON> {
  const cached = collectionCache.get(set);
  if (cached) return cached;

  try {
    const loaded = await import(`@iconify-json/${set}/icons.json`);
    const data = (loaded.default ?? loaded) as IconifyJSON;
    collectionCache.set(set, data);

    return data;
  } catch {
    throw new Error(`Missing icon set "@iconify-json/${set}". Add it with bun add -d @iconify-json/${set}`);
  }
}

function collectIconRefs(): IconRef[] {
  const seen = new Set<string>();
  const refs: IconRef[] = [];

  for (const file of SOURCE_GLOB.scanSync({ cwd: SRC_DIR, onlyFiles: true })) {
    if (file.startsWith('icons/') || file.startsWith('icons\\')) continue;

    const source = readFileSync(join(SRC_DIR, file), 'utf8');
    IMPORT_PATTERN.lastIndex = 0;

    let match: RegExpExecArray | null;
    while ((match = IMPORT_PATTERN.exec(source))) {
      const set = match[1];
      const name = match[2];
      const key = `${set}/${name}`;
      if (seen.has(key)) continue;

      seen.add(key);
      refs.push({ set, name });
    }
  }

  return refs;
}

function renderIconFile({ set, name }: IconRef, body: string, viewBox: string): string {
  const component = toComponentName(name);

  return `${GENERATED_HEADER}
export default function ${component}(props) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="1em"
      height="1em"
      viewBox="${viewBox}"
      {...props}
      dangerouslySetInnerHTML={{ __html: ${JSON.stringify(body)} }}
    />
  );
}

${component}.displayName = "${set}:${name}";
`;
}

function listGeneratedIconFiles(dir: string = ICONS_DIR): string[] {
  if (!existsSync(dir)) return [];

  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listGeneratedIconFiles(fullPath));
      continue;
    }

    if (!entry.name.endsWith('.jsx')) continue;

    const contents = readFileSync(fullPath, 'utf8');
    if (contents.startsWith(GENERATED_HEADER)) files.push(fullPath);
  }

  return files;
}

function removeEmptyDirs(dir: string): void {
  if (!existsSync(dir) || dir === ICONS_DIR) return;

  const entries = readdirSync(dir);
  if (entries.length > 0) return;

  rmSync(dir);
  removeEmptyDirs(dirname(dir));
}

async function writeIcon(ref: IconRef): Promise<'written' | 'unchanged'> {
  const collection = await loadCollection(ref.set);
  const data = getIconData(collection, ref.name);
  if (!data) {
    throw new Error(`Unknown icon "${ref.set}:${ref.name}"`);
  }

  const svg = iconToSVG(data);
  const viewBox = svg.attributes.viewBox || '0 0 24 24';
  const contents = renderIconFile(ref, svg.body, viewBox);
  const filePath = iconPath(ref);

  mkdirSync(dirname(filePath), { recursive: true });

  const previous = existsSync(filePath) ? readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n') : '';
  if (previous === contents) return 'unchanged';

  writeFileSync(filePath, contents);

  return 'written';
}

const refs = collectIconRefs();
if (refs.length === 0) {
  console.log('No ~icons imports found.');
  process.exit(0);
}

const keep = new Set(refs.map(iconKey));
let written = 0;
let unchanged = 0;

for (const ref of refs) {
  const result = await writeIcon(ref);
  if (result === 'written') written += 1;
  else unchanged += 1;
}

let pruned = 0;
for (const filePath of listGeneratedIconFiles()) {
  const key = relative(ICONS_DIR, filePath).replaceAll('\\', '/').replace(/\.jsx$/, '');
  if (keep.has(key)) continue;

  rmSync(filePath);
  removeEmptyDirs(dirname(filePath));
  pruned += 1;
}

console.log(`Icons: ${written} written, ${unchanged} unchanged, ${pruned} pruned (${refs.length} used).`);
